title: Yeeun Shim
description: Backend Engineer
site_title: Yenny's blog

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: yennyshim
blog_url: 
email: yenny_s@naver.com
keybase_username: yeeun
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 